datasource_list: [ NoCloud, None ]
network:
  version: 1
  config:
    - type: physical
      name: id0
      mac_address: 52:54:00:bf:b2:d8
      subnets:
         - type: static
           address: 192.168.100.100/24
           gateway: 192.168.100.1
#  version: 2
#  ethernets:
#    id0:
#      match:
#        macaddress: ${ACCESS_MAC_ADDRESS}
#      dhcp4: false
#      addresses:
#        - ${ACCESS_IP_CIDR}
#      gateway4: ${ACCESS_GW}
#      nameservers:
#        addresses: [$DNS_SERVER]
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDEMMYsge3feKSQVDmGEe+14KAthSXWcqVrI+5+QBoO8pu7z6dINGE3w5jatICz9Lm92mXXZN1teM52bCWpDRyjt8L3jKfgHPeHoN6DSbQqKQOYDvl0IsUixUH7f2McSASnwP15ecj0uLXXGLmoqL5OZKje8ldzgS3TDLJDiqM7auYuFx4IggQSay2dX+JfwGv/OW0NeHNCqcv+EQ1LW7Y0rhIDYZ5nZWLjSMiJhvX7kITdBqKHrEUscWrDwSEAd2bCROFDMDxg70P8PkiTmkonaYzOVVDzovHI64SMggfL9zLYHueTsC0yoylWwX/u9WaqK2NaDvyH3zmNuacr6wmz}
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3C2uVTnDxiDZKalG+DaAAh7JE20cGJY38Dbx3mYB5YfvPxTfmZB7LdE6LWtUPTBnoWkXmv0rkuvpgIfG76ceDt5EUzTqBcte8WRQkc3Pa5W3UgFhF5XvFEqsQBNEKtqpBWXsyE9yacV1M8wA17VhhPo4hB9tedT0+reCEIG7NlGTM81VXk3dPySI1MCXZsBiLV5ut02rhsdFlhI+V1bAiBCWp3yC7S+ZPufuinP2uYagA+Ex/XCaIZoUwTjTR3WMiiM7+ke7v/SJVDHVNJSwmnWAJmy2IjK0mVfdI7c4h/k8Wfx3m/ZE13vASPWCsKz0zoyFrpYLMLhWTuOyHuTHt jingvar@Bzzz

resize_rootfs: false
disk_setup:
   /dev/sda:
      table_type: mbr
      layout:
         - [33,82]
      overwrite: True
fs_setup:
   - label: datadisk
     filesystem: ext4
     device: /dev/sda1
     replace_fs: ext4
   - cmd: mkfs -t %(filesystem)s -L %(label)s %(device)s
mounts:
  - [ /dev/sda, "/datadisk", auto, "defaults,noexec,nofail" ]

runcmd:
  - iptables -P FORWARD ACCEPT
  - mkdir /datadisk/docker
  - mkdir /datadisk/kubelet
  - mkdir /var/lib/docker
  - mkdir /var/lib/kubelet
  - mount /datadisk/docker /var/lib/docker --bind
  - mount /datadisk/kubelet /var/lib/kubelet --bind
  - echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" > /etc/apt/sources.list.d/kubernetes.list
  - echo "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update --allow-insecure-repositories && apt-get install -y --no-install-recommends --allow-unauthenticated docker-ce kubelet kubeadm kubectl
  - [ kubeadm, config, images, pull ]
  - [ kubeadm, init, --pod-network-cidr=192.168.0.0/24, --ignore-preflight-errors, 'SystemVerification' ]
  - [ kubectl, --kubeconfig, /etc/kubernetes/admin.conf, apply, -f, 'https://docs.projectcalico.org/v3.8/manifests/calico.yaml' ]
  - [ kubectl, --kubeconfig, /etc/kubernetes/admin.conf, taint, nodes, --all, node-role.kubernetes.io/master- ]
  - [ chmod, +r, /etc/kubernetes/admin.conf ]
  - iptables -P FORWARD ACCEPT
  - [ touch, /deployed ]
